version: '3.4'

services:
  timerservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8082:8080"
      - "8083:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - postgres
    networks:
      - backend

  blazorapp2:
    image: ${DOCKER_REGISTRY-}blazorapp2
    build:
      context: .
      dockerfile: BlazorApp2/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8084:80"
    networks:
      - frontend

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5755dazai
      POSTGRES_DB: Timer
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
     driver: bridge
  frontend:
    driver: bridge
