version: '3.8' 

services:
  timerservice.api:
    build:
      context: ./TimerService.API
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
    ports:
      - "8080:80"  
      - "8081:443"  
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - postgres  

  blazorapp2:
    build:
      context: ./BlazorApp2
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
    ports:
      - "8080:80"  
      - "8081:443"  
    depends_on:
      - timerservice.api  

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postger
      POSTGRES_PASSWORD: 5755dazai
      POSTGRES_DB: Timer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
