version: '3.4'

services:
  timerservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  blazorapp2:
    image: ${DOCKER_REGISTRY-}blazorapp2
    build:
      context: .
      dockerfile: BlazorApp2/Dockerfile2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
