version: '3.4'

services:
  timerservice.api:
    image: ${DOCKER_REGISTRY-}timerserviceapi
    build:
      context: .
      dockerfile: TimerService.API/Dockerfile
  blazorapp2:
    image: ${DOCKER_REGISTRY-}blazorapp2
    build:
        context: .
        dockerfile: BlazorApp2/Dockerfile
